#Download Linux
FROM ubuntu:20.04

ARG OPENCV_VERSION=3.4.6

# Build Environment Variables
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York
ENV NODE_OPTIONS=--max_old_space_size=4096

# Update and Upgrade Image
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y build-essential cmake unzip wget pkg-config git curl
RUN curl -sL https://deb.nodesource.com/setup_15.x | bash -
RUN apt-get install -y nodejs

RUN apt-get install -y libjpeg-dev libpng-dev
RUN apt-get install -y libavcodec-dev libavformat-dev libswscale-dev
RUN apt-get install -y libgtk2.0-dev libcanberra-gtk* libgtk-3-dev
RUN apt-get install -y libxvidcore-dev libx264-dev
RUN apt-get install -y python3-dev python3-numpy python3-pip
RUN apt-get install -y libtbb2 libtbb-dev libdc1394-22-dev \
                          libv4l-dev v4l-utils \
                          libopenblas-dev libatlas-base-dev libblas-dev \
                          liblapack-dev gfortran libhdf5-dev \
                          libprotobuf-dev libgoogle-glog-dev libgflags-dev \
                          protobuf-compiler 

# Download opencv
RUN mkdir -p /opt && cd /opt && \
  wget -O opencv.zip https://github.com/opencv/opencv/archive/$OPENCV_VERSION.zip && \
  wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/$OPENCV_VERSION.zip && \
  unzip opencv.zip && rm opencv.zip && \
  unzip opencv_contrib.zip && rm opencv_contrib.zip && \
  mv /opt/opencv-$OPENCV_VERSION /opt/opencv && mv /opt/opencv_contrib-$OPENCV_VERSION /opt/opencv_contrib


# Build OPENCV
RUN cd /opt/opencv/ && mkdir build && cd build &&\
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D OPENCV_EXTRA_MODULES_PATH=/opt/opencv_contrib/modules \
        -D ENABLE_NEON=ON \
        -D WITH_FFMPEG=ON \
        -D WITH_GSTREAMER=ON \
        -D WITH_TBB=ON \
        -D BUILD_TBB=ON \
        -D BUILD_TESTS=OFF \
        -D WITH_EIGEN=OFF \
        -D WITH_V4L=ON \
        -D WITH_LIBV4L=ON \
        -D WITH_VTK=OFF \
        -D WITH_QT=OFF \
        -D OPENCV_ENABLE_NONFREE=ON \
        -D INSTALL_C_EXAMPLES=OFF \
        -D INSTALL_PYTHON_EXAMPLES=OFF \
        -D BUILD_NEW_PYTHON_SUPPORT=ON \
        -D BUILD_opencv_python3=TRUE \
        -D OPENCV_GENERATE_PKGCONFIG=ON \
        -D BUILD_EXAMPLES=OFF ..

RUN cd /opt/opencv/build && make -j4 && make install && ldconfig && apt-get update

# Setup Jada Application
# Get Jada Code
RUN git clone https://github.com/reddingk/Jada.git Jada

# Clean Extra Files Build Files
RUN rm /Jada/package.json && \
    rm /Jada/package-lock.json 

# Copy Build Files
COPY /dockerfiles/package.json /Jada/package.json
RUN mkdir -p /public

# Copy Env File
COPY .env /Jada/.env

# Remove Development Files
RUN rm -r /Jada/dockerfiles && \
    rm /Jada/jadacmd.js && \
    rm /Jada/jadaEx.js

# Install Application Packages
RUN cd /Jada; npm install

# Copy H264 opencv file
COPY /dockerfiles/libopenh264-1.7.0-linux64.4.so /usr/local/lib

# Clean Up Packages
RUN apt-get remove -y unzip wget cmake

# Run Application
EXPOSE  1003

WORKDIR /Jada
CMD ["npm", "start"]